//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortening.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class urls
    {
        public long id { get; set; }
        public string actualUrl { get; set; }
        public Nullable<int> visits { get; set; }
    }
}
